### ISSUE TITLE
corrsearch.py

### ISSUE THREAD

**Issue by blazvicic** [pyrocko/contrib-snufflings#20]

**Comment by blazvicic** [comment]
bah, it was stupidity from my side... I tried to delete the issue, but failed even at that... what I did was in the browser I right clicked and selected download file (.py) which downloaded a html part of the website. 

now it works without any problem!

**Comment by HerrMuellerluedenscheid** [comment]
I just reread the message and realized it comes from the logher. So I
assume that the error message is in deed complete. Can you check your
.snuffling directory and remove the corrsearch.pyc file and try again?
Maybe there is a broken link to that snuffling and a leftover .pyc. could
you also update the snufflings, if you haven't done that, yet?

Marius

Am 09.08.2017 9:59 vorm. schrieb "Marius Kriegerowski" <
marius.kriegerowski@gmail.com>:

**Comment by HerrMuellerluedenscheid** [comment]
Great!

By the way: you can also clone the entire repository and either run

    Python setup.py link corrsearch

To create a symbolic link at .snufflings in your home directory for that
snuffling. You can also drop the last argument so that all snufflings are
linked. This makes it a little easier to keep your snufflings updated.

Happy snuffling!

Am 09.08.2017 10:06 vorm. schrieb "Marius Kriegerowski" <
marius.kriegerowski@gmail.com>:
